/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.*;
import java.awt.*;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author barce
 */
public class DataFill extends javax.swing.JFrame {



    CardLayout cards = new CardLayout();

    /**
     * Creates new form HardwareData
     */
    public DataFill() {
        initComponents();
        jcards.setLayout(cards);

        cleanData(0);

        cards.show(jcards, "menu");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcards = new javax.swing.JPanel();
        p_menu = new javax.swing.JPanel();
        menu_bttn_equipo = new javax.swing.JButton();
        menu_bttn_empleado = new javax.swing.JButton();
        menu_bttn_cancel = new javax.swing.JButton();
        p_emp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        datafill_emp_tf_nombre = new javax.swing.JTextField();
        datafill_emp_tf_ubicacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        datafill_emp_tf_area = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        datafill_emp_tf_direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        datafill_emp_tf_cargo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        datafill_emp_bttn_save = new javax.swing.JButton();
        datafill_emp_tf_clean = new javax.swing.JButton();
        datafill_emp_bttn_cancel = new javax.swing.JButton();
        p_gabinete = new javax.swing.JPanel();
        datafill_gab_save = new javax.swing.JButton();
        datafill_gab_bttn_clean = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        datafill_gab_cb_resguardante = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        datafill_gab_tf_marca = new javax.swing.JTextField();
        datafill_gab_tf_inv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        datafill_gab_tf_modelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        datafill_gab_tf_procesador = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        datafill_gab_tf_ram = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        datafill_gab_tf_discoduro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        datafill_gab_tf_office = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        datafill_gab_tf_win = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        datafill_gab_cb_status = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        datafill_gab_tf_serie = new javax.swing.JTextField();
        datafill_gab_bttn_cancel = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datafill_gab_ta_observaciones = new javax.swing.JTextArea();
        p_perifericos = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        p_impresoras = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcards.setLayout(new java.awt.CardLayout());

        menu_bttn_equipo.setText("Equipo");
        menu_bttn_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_bttn_equipoActionPerformed(evt);
            }
        });

        menu_bttn_empleado.setText("Empleado");
        menu_bttn_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_bttn_empleadoActionPerformed(evt);
            }
        });

        menu_bttn_cancel.setText("Cancelar");
        menu_bttn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_bttn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_menuLayout = new javax.swing.GroupLayout(p_menu);
        p_menu.setLayout(p_menuLayout);
        p_menuLayout.setHorizontalGroup(
            p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu_bttn_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(p_menuLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(menu_bttn_cancel)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_menuLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(menu_bttn_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );
        p_menuLayout.setVerticalGroup(
            p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_menuLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(menu_bttn_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(menu_bttn_cancel)
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_menuLayout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(menu_bttn_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(381, Short.MAX_VALUE)))
        );

        jcards.add(p_menu, "menu");

        jLabel1.setText("Nombre");

        jLabel2.setText("Ubicacion");

        jLabel3.setText("Area");

        jLabel4.setText("Direccion");

        jLabel5.setText("Cargo");

        datafill_emp_bttn_save.setText("Guardar");
        datafill_emp_bttn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafill_emp_bttn_saveActionPerformed(evt);
            }
        });

        datafill_emp_tf_clean.setText("Limpiar");
        datafill_emp_tf_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafill_emp_tf_cleanActionPerformed(evt);
            }
        });

        datafill_emp_bttn_cancel.setText("Cancelar");
        datafill_emp_bttn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafill_emp_bttn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_empLayout = new javax.swing.GroupLayout(p_emp);
        p_emp.setLayout(p_empLayout);
        p_empLayout.setHorizontalGroup(
            p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_empLayout.createSequentialGroup()
                .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_empLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(p_empLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datafill_emp_tf_area, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_empLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datafill_emp_tf_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_empLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(datafill_emp_tf_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(p_empLayout.createSequentialGroup()
                                        .addComponent(datafill_emp_bttn_save)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(datafill_emp_tf_clean)
                                        .addGap(61, 61, 61))))))
                    .addGroup(p_empLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datafill_emp_tf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_empLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datafill_emp_tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_empLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(datafill_emp_bttn_cancel)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        p_empLayout.setVerticalGroup(
            p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_empLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(datafill_emp_tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(datafill_emp_tf_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datafill_emp_tf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(datafill_emp_tf_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(datafill_emp_tf_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(p_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datafill_emp_bttn_save)
                    .addComponent(datafill_emp_tf_clean))
                .addGap(32, 32, 32)
                .addComponent(datafill_emp_bttn_cancel)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jcards.add(p_emp, "emp");

        datafill_gab_save.setText("Guardar");
        datafill_gab_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafill_gab_saveActionPerformed(evt);
            }
        });

        datafill_gab_bttn_clean.setText("Limpiar");
        datafill_gab_bttn_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafill_gab_bttn_cleanActionPerformed(evt);
            }
        });

        jLabel6.setText("Resguardante");

        datafill_gab_cb_resguardante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Marca");

        jLabel8.setText("No. Inventario");

        jLabel9.setText("Modelo");

        jLabel10.setText("Componentes");

        jLabel11.setText("Procesador");

        jLabel12.setText("RAM");

        jLabel13.setText("Disco Duro");

        jLabel14.setText("Office");

        jLabel15.setText("Windows");

        datafill_gab_cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUENO", "OBSOLETO", "BAJA" }));
        datafill_gab_cb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafill_gab_cb_statusActionPerformed(evt);
            }
        });

        jLabel16.setText("Estado");

        jLabel17.setText("No. de Serie");

        datafill_gab_bttn_cancel.setText("Cancelar");
        datafill_gab_bttn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafill_gab_bttn_cancelActionPerformed(evt);
            }
        });

        jLabel18.setText("Observaciones");

        datafill_gab_ta_observaciones.setColumns(20);
        datafill_gab_ta_observaciones.setRows(5);
        jScrollPane1.setViewportView(datafill_gab_ta_observaciones);

        javax.swing.GroupLayout p_gabineteLayout = new javax.swing.GroupLayout(p_gabinete);
        p_gabinete.setLayout(p_gabineteLayout);
        p_gabineteLayout.setHorizontalGroup(
            p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gabineteLayout.createSequentialGroup()
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_gabineteLayout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(p_gabineteLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(datafill_gab_cb_resguardante, 0, 346, Short.MAX_VALUE))
                                .addGroup(p_gabineteLayout.createSequentialGroup()
                                    .addGap(159, 159, 159)
                                    .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(datafill_gab_tf_office, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gabineteLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(datafill_gab_tf_marca))
                                .addGroup(p_gabineteLayout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(datafill_gab_tf_modelo))
                                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(datafill_gab_bttn_cancel)
                                    .addGroup(p_gabineteLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(datafill_gab_cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(p_gabineteLayout.createSequentialGroup()
                                    .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10))
                                    .addGap(18, 18, 18)
                                    .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(datafill_gab_tf_inv, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                        .addComponent(datafill_gab_tf_serie)))
                                .addGroup(p_gabineteLayout.createSequentialGroup()
                                    .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(datafill_gab_tf_procesador, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(p_gabineteLayout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(112, 112, 112)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(p_gabineteLayout.createSequentialGroup()
                                            .addComponent(datafill_gab_tf_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(datafill_gab_tf_discoduro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(datafill_gab_tf_win, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))))
                    .addGroup(p_gabineteLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(datafill_gab_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datafill_gab_bttn_clean)
                        .addGap(103, 103, 103)))
                .addGap(119, 119, 119))
        );
        p_gabineteLayout.setVerticalGroup(
            p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_gabineteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_gabineteLayout.createSequentialGroup()
                        .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(datafill_gab_cb_resguardante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(datafill_gab_tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(datafill_gab_tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(datafill_gab_tf_inv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(datafill_gab_tf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_gabineteLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datafill_gab_tf_procesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_gabineteLayout.createSequentialGroup()
                        .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datafill_gab_tf_ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datafill_gab_tf_discoduro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datafill_gab_tf_win, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datafill_gab_tf_office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(datafill_gab_cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_gabineteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datafill_gab_save)
                    .addComponent(datafill_gab_bttn_clean))
                .addGap(18, 18, 18)
                .addComponent(datafill_gab_bttn_cancel)
                .addGap(30, 30, 30))
        );

        jcards.add(p_gabinete, "gab");

        jLabel19.setText("Marca");

        jLabel20.setText("No. Inventario");

        jLabel21.setText("Modelo");

        jLabel22.setText("No. de Serie");

        jLabel23.setText("Tipo");

        jLabel24.setText("Observaciones");

        jLabel25.setText("Estado");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUENO", "OBSOLETO", "BAJA" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "TECLADO", "MOUSE" }));

        jButton1.setText("Guardar");

        jButton2.setText("Limpiar");

        jButton3.setText("Cancelar");

        jLabel26.setText("Resguardante");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout p_perifericosLayout = new javax.swing.GroupLayout(p_perifericos);
        p_perifericos.setLayout(p_perifericosLayout);
        p_perifericosLayout.setHorizontalGroup(
            p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_perifericosLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(117, 117, 117))
            .addGroup(p_perifericosLayout.createSequentialGroup()
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_perifericosLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_perifericosLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_perifericosLayout.createSequentialGroup()
                                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(p_perifericosLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton3)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        p_perifericosLayout.setVerticalGroup(
            p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_perifericosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(29, 29, 29)
                .addGroup(p_perifericosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jcards.add(p_perifericos, "card5");

        jButton4.setText("Limpiar");

        jButton5.setText("Cancelar");

        jButton6.setText("Guardar");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUENO", "OBSOLETO", "BAJA" }));

        jLabel27.setText("Estado");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel28.setText("Observaciones");

        jLabel29.setText("No. de Serie");

        jLabel30.setText("Modelo");

        jLabel31.setText("No. Inventario");

        jLabel32.setText("Codigo");

        jLabel33.setText("Tipo");

        jLabel34.setText("Marca");

        jLabel35.setText("Resguardante");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "HP", "Epson", "Brother" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una opcion", "TINTA", "TONER/CARTUCHO" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout p_impresorasLayout = new javax.swing.GroupLayout(p_impresoras);
        p_impresoras.setLayout(p_impresorasLayout);
        p_impresorasLayout.setHorizontalGroup(
            p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_impresorasLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(117, 117, 117))
            .addGroup(p_impresorasLayout.createSequentialGroup()
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_impresorasLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton5))
                    .addGroup(p_impresorasLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_impresorasLayout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_impresorasLayout.createSequentialGroup()
                                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField5)
                                    .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(p_impresorasLayout.createSequentialGroup()
                                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        p_impresorasLayout.setVerticalGroup(
            p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_impresorasLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(29, 29, 29)
                .addGroup(p_impresorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jcards.add(p_impresoras, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datafill_emp_bttn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafill_emp_bttn_saveActionPerformed
        // TODO add your handling code here:
        saveData(1);
    }//GEN-LAST:event_datafill_emp_bttn_saveActionPerformed

    private void datafill_emp_tf_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafill_emp_tf_cleanActionPerformed
        // TODO add your handling code here:
        cleanData(1);
    }//GEN-LAST:event_datafill_emp_tf_cleanActionPerformed

    private void datafill_gab_cb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafill_gab_cb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datafill_gab_cb_statusActionPerformed

    private void menu_bttn_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_bttn_empleadoActionPerformed
        // TODO add your handling code here:
        cleanData(1);
        cards.show(jcards, "emp");
    }//GEN-LAST:event_menu_bttn_empleadoActionPerformed

    private void menu_bttn_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_bttn_equipoActionPerformed
        // TODO add your handling code here:
        cleanData(2);
        cards.show(jcards, "gab");
    }//GEN-LAST:event_menu_bttn_equipoActionPerformed

    private void menu_bttn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_bttn_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menu_bttn_cancelActionPerformed

    private void datafill_emp_bttn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafill_emp_bttn_cancelActionPerformed
        // TODO add your handling code here:
        cards.show(jcards, "menu");
    }//GEN-LAST:event_datafill_emp_bttn_cancelActionPerformed

    private void datafill_gab_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafill_gab_saveActionPerformed
        // TODO add your handling code here:
        saveData(2);
    }//GEN-LAST:event_datafill_gab_saveActionPerformed

    private void datafill_gab_bttn_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafill_gab_bttn_cleanActionPerformed
        // TODO add your handling code here:
        cleanData(2);
    }//GEN-LAST:event_datafill_gab_bttn_cleanActionPerformed

    private void datafill_gab_bttn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafill_gab_bttn_cancelActionPerformed
        // TODO add your handling code here:
        cards.show(jcards, "menu");
    }//GEN-LAST:event_datafill_gab_bttn_cancelActionPerformed

    private void cleanData(int op){
        switch (op){
            case 0:
                cleanData(1);
                cleanData(2);
                break;
            case 1:
                try{
                    datafill_emp_tf_direccion.setText("");
                    datafill_emp_tf_area.setText("");
                    datafill_emp_tf_cargo.setText("");
                    datafill_emp_tf_nombre.setText("");
                    datafill_emp_tf_ubicacion.setText("");
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                break;
            case 2:
                String sql = "SELECT nombre FROM datos_resguardante ORDER BY NOMBRE";
                try{
                    try(var conn = BD.Connect.open();
                        var stmt = conn.createStatement();) {

                        ResultSet chk = stmt.executeQuery(sql);

                        datafill_gab_cb_resguardante.removeAllItems();

                        datafill_gab_cb_resguardante.addItem("Resguardante");

                        while (chk.next()) {
                            datafill_gab_cb_resguardante.addItem(chk.getString("nombre"));
                        }
                    }catch (SQLException es){
                        JOptionPane.showMessageDialog(null, es);
                    }

                    datafill_gab_cb_resguardante.setSelectedIndex(0);
                    datafill_gab_cb_status.setSelectedIndex(0);
                    datafill_gab_tf_marca.setText("");
                    datafill_gab_tf_modelo.setText("");
                    datafill_gab_tf_discoduro.setText("");
                    datafill_gab_tf_inv.setText("");
                    datafill_gab_tf_office.setText("");
                    datafill_gab_tf_procesador.setText("");
                    datafill_gab_tf_ram.setText("");
                    datafill_gab_tf_serie.setText("");
                    datafill_gab_tf_win.setText("");
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                break;
        }
    }

    /**
     * Saves data to the database according to the option.
     *
     * option:
     *   1 -> Save EMPLOYEE (p_emp) into datos_resguardante
     *   2 -> Save GABINETE (p_gabinete) into hardware_gabinete
     *
     * Notes:
     * - Preserves user input as-is (no trimming or case transformations).
     * - Allows blanks and spaces in all fields.
     * - Clears only the corresponding panel after successful save.
     */
    private void saveData(int option) {
        switch (option) {
            case 1: { // EMPLOYEE (p_emp) -> datos_resguardante
                final String sqlEmp =
                        "INSERT INTO datos_resguardante " +
                                " (nombre, departamento, direccion, cargo, ubicacion_fisica, extension, correo) " +
                                "VALUES (?, ?, ?, ?, ?, ?, ?)";

                final String vNombre     = datafill_emp_tf_nombre.getText();
                final String vArea       = datafill_emp_tf_area.getText();
                final String vDireccion  = datafill_emp_tf_direccion.getText();
                final String vCargo      = datafill_emp_tf_cargo.getText();
                final String vUbicacion  = datafill_emp_tf_ubicacion.getText();

                try (var conn = BD.Connect.open();
                     var ps   = conn.prepareStatement(sqlEmp)) {

                    ps.setString(1, vNombre);
                    ps.setString(2, vArea);
                    ps.setString(3, vDireccion);
                    ps.setString(4, vCargo);
                    ps.setString(5, vUbicacion);
                    ps.setNull(6, java.sql.Types.VARCHAR); // extension not in UI
                    ps.setNull(7, java.sql.Types.VARCHAR); // correo not in UI

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Employee saved.");
                    cleanData(1);

                } catch (java.sql.SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                break;
            }

            case 2: { // GABINETE (p_gabinete) -> hardware_gabinete
                final String sqlGab =
                        "INSERT INTO hardware_gabinete " +
                                " (resguardante, marca, modelo, no_inventario, numero_serie, componentes, status, observaciones) " +
                                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

                final Object selResguardante = datafill_gab_cb_resguardante.getSelectedItem();
                final Object selStatus       = datafill_gab_cb_status.getSelectedItem();

                final String vResguardante = (selResguardante == null) ? null : selResguardante.toString();
                final String vStatus       = (selStatus == null)       ? null : selStatus.toString();

                final String vMarca       = datafill_gab_tf_marca.getText();
                final String vModelo      = datafill_gab_tf_modelo.getText();
                final String vInventario  = datafill_gab_tf_inv.getText();
                final String vSerie       = datafill_gab_tf_serie.getText();

                final String vProcesador  = datafill_gab_tf_procesador.getText();
                final String vRam         = datafill_gab_tf_ram.getText();
                final String vDisco       = datafill_gab_tf_discoduro.getText();
                final String vWin         = datafill_gab_tf_win.getText();
                final String vOffice      = datafill_gab_tf_office.getText();

                // Build the "componentes" string in the required order with a space after each comma
                final String vComponentes =
                        (vProcesador == null ? "" : vProcesador) + ", " +
                                (vRam        == null ? "" : vRam)        + ", " +
                                (vDisco      == null ? "" : vDisco)      + ", " +
                                (vWin        == null ? "" : vWin)        + ", " +
                                (vOffice     == null ? "" : vOffice);

                final String vObservaciones = datafill_gab_ta_observaciones.getText(); // Will be added later

                try (var conn = BD.Connect.open();
                     var ps   = conn.prepareStatement(sqlGab)) {

                    // Resolve FK: resguardante (nullable if no selection)
                    Integer resguardanteId = resolveResguardanteIdByName(conn, vResguardante);
                    if (resguardanteId == null) {
                        ps.setNull(1, java.sql.Types.INTEGER);
                    } else {
                        ps.setInt(1, resguardanteId);
                    }

                    ps.setString(2, vMarca);
                    ps.setString(3, vModelo);
                    ps.setString(4, vInventario);
                    ps.setString(5, vSerie);
                    ps.setString(6, vComponentes);
                    ps.setString(7, vStatus);
                    ps.setString(8, vObservaciones); // observaciones placeholder

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Gabinete saved.");
                    cleanData(2);

                } catch (java.sql.SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                break;
            }
            
            case 3:{
                
                break;
            }
            default:
                JOptionPane.showMessageDialog(this, "Invalid save option: " + option);
        }
        MainInterface m = new MainInterface();
        m.sel();
    }

    /**
     * Looks up the datos_resguardante.id by the given name.
     * Returns null if the name is null, blank, or not found.
     */
    private Integer resolveResguardanteIdByName(java.sql.Connection conn, String nombre) {
        if (nombre == null || nombre.isEmpty() || "Seleciona un Resguardante".equals(nombre)) {
            return null;
        }

        final String sqlFind = "SELECT id FROM datos_resguardante WHERE nombre = ? LIMIT 1";
        try (var ps = conn.prepareStatement(sqlFind)) {
            ps.setString(1, nombre);
            try (var rs = ps.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("id");
                }
            }
        } catch (java.sql.SQLException ex) {
            System.err.println("resolveResguardanteIdByName error: " + ex.getMessage());
        }
        return null;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataFill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataFill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datafill_emp_bttn_cancel;
    private javax.swing.JButton datafill_emp_bttn_save;
    private javax.swing.JTextField datafill_emp_tf_area;
    private javax.swing.JTextField datafill_emp_tf_cargo;
    private javax.swing.JButton datafill_emp_tf_clean;
    private javax.swing.JTextField datafill_emp_tf_direccion;
    private javax.swing.JTextField datafill_emp_tf_nombre;
    private javax.swing.JTextField datafill_emp_tf_ubicacion;
    private javax.swing.JButton datafill_gab_bttn_cancel;
    private javax.swing.JButton datafill_gab_bttn_clean;
    private javax.swing.JComboBox<String> datafill_gab_cb_resguardante;
    private javax.swing.JComboBox<String> datafill_gab_cb_status;
    private javax.swing.JButton datafill_gab_save;
    private javax.swing.JTextArea datafill_gab_ta_observaciones;
    private javax.swing.JTextField datafill_gab_tf_discoduro;
    private javax.swing.JTextField datafill_gab_tf_inv;
    private javax.swing.JTextField datafill_gab_tf_marca;
    private javax.swing.JTextField datafill_gab_tf_modelo;
    private javax.swing.JTextField datafill_gab_tf_office;
    private javax.swing.JTextField datafill_gab_tf_procesador;
    private javax.swing.JTextField datafill_gab_tf_ram;
    private javax.swing.JTextField datafill_gab_tf_serie;
    private javax.swing.JTextField datafill_gab_tf_win;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel jcards;
    private javax.swing.JButton menu_bttn_cancel;
    private javax.swing.JButton menu_bttn_empleado;
    private javax.swing.JButton menu_bttn_equipo;
    private javax.swing.JPanel p_emp;
    private javax.swing.JPanel p_gabinete;
    private javax.swing.JPanel p_impresoras;
    private javax.swing.JPanel p_menu;
    private javax.swing.JPanel p_perifericos;
    // End of variables declaration//GEN-END:variables
}
