/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import invmauricio.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import BD.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barce
 */
public class MainInterface extends javax.swing.JFrame {

    
    private final String devpass = "Coreolis_19";
    private String version = "1.17.20.AA10L25";
    private int clickcount = 0, clickc = 0;
    private Connect con = new Connect();
    private SqliteQuery sqlq = new SqliteQuery();
    private String[] filt = new String[7];
    private int co = 0;//
    
    private ComboBoxModel cbxmarea;
    private ComboBoxModel cbxmstatus;
    private ComboBoxModel cbxmdir;
    private ComboBoxModel cbxmubi;
    private ComboBoxModel cbxmname;
    private ComboBoxModel cbxmnoinv;
    
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        System.out.println(MacAddressUtil.getMacAddress());
        jInternalFrame1.pack();
        jInternalFrame1.hide();
        lbl_version.setText(lbl_version.getText()+version);
        
        this.cbxmarea = cbx_area.getModel();
        this.cbxmstatus = cbx_status.getModel();
        this.cbxmdir = cbx_dir.getModel();
        this.cbxmubi = cbx_ubicacion.getModel();
        this.cbxmname = cbx_name.getModel();
        this.cbxmnoinv = cbx_ninv.getModel();

        sqlq.dbConnect();
        sqlq.createdbTable();
        cbx_init();
        sel();
        
        //cbx_area.setVisible(false);
        //cbx_dir.setVisible(false);
        //cbx_name.setVisible(false);
        //cbx_ninv.setVisible(false);
        //cbx_status.setVisible(false);
        //cbx_ubicacion.setVisible(false);
    }

    public String getVersion() {
        return version;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        bttn_dev = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbx_ninv = new javax.swing.JComboBox<>();
        cbx_name = new javax.swing.JComboBox<>();
        cbx_dir = new javax.swing.JComboBox<>();
        cbx_area = new javax.swing.JComboBox<>();
        cbx_ubicacion = new javax.swing.JComboBox<>();
        cbx_status = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tf_caracteristicas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        counting_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_version = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><h1 style=\"text-align: center\">Acerca</h1>         <div><p>Programa hecho por Stratos Dilligennce para la coordinación de informática de <strong>COAPATAP</strong> solicitado por <strong>Mauricio Ochoa</strong> con las siguientes especificaciones:</p>          <p><strong>Solicitud de desarrollo de interfaz local para visualización de base de datos</strong></p>         <p>Se solicita el desarrollo de una interfaz gráfica local que permita la visualización estructurada de los datos contenidos en la base de datos correspondiente a la Oficina Matriz. La interfaz deberá mostrar los siguientes campos:</p>                  <ul>             <li>Número de inventario</li>             <li>Nombre</li>             <li>Características</li>             <li>Dirección</li>             <li>Área</li>             <li>Ubicación física</li>             <li>Descripción del equipo</li>             <li>Estado</li>         </ul>          <p><strong>Requisitos técnicos:</strong></p>         <ul>             <li>La interfaz debe ejecutarse de forma local en equipos de escritorio (Windows).</li>             <li>Debe estar conectada a la base de datos previamente armada por el mismo programador.</li>             <li>El diseño debe ser amigable y funcional, permitiendo ordenar columnas y, de ser posible, filtrar/buscar registros por cualquiera de los campos listados.</li>             <li>No es necesario acceso web ni conexión remota.</li>             <li>No requiere permisos de edición, únicamente visualización, por el momento.</li>         </ul>         <p>Solicitud hecha el día <strong>25/07/2025</strong></p>\t<p>Entrega acordada el día <strong>17/10/2025</strong></p>\t<p>Entrega de avances <strong>cada 2 viernes</strong></p></div></html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 375));
        jScrollPane1.setViewportView(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("<h1>Acerca</h1>\n        <p>Programa hecho por Stratos Dilligence para la coordinación de informática de <strong>COAPATAP</strong> solicitado por <strong>Mauricio Ochoa</strong> con las siguientes especificaciones:</p>\n\n        <p><strong>Solicitud de desarrollo de interfaz local para visualización de base de datos</strong></p>\n        <p>Se solicita el desarrollo de una interfaz gráfica local que permita la visualización estructurada de los datos contenidos en la base de datos correspondiente a la Oficina Matriz. La interfaz deberá mostrar los siguientes campos:</p>\n        \n        <ul>\n            <li>Número de inventario</li>\n            <li>Nombre</li>\n            <li>Características</li>\n            <li>Dirección</li>\n            <li>Área</li>\n            <li>Ubicación física</li>\n            <li>Descripción del equipo</li>\n            <li>Estado</li>\n        </ul>\n\n        <p><strong>Requisitos técnicos:</strong></p>\n        <ul>\n            <li>La interfaz debe ejecutarse de forma local en equipos de escritorio (Windows).</li>\n            <li>Debe estar conectada a la base de datos previamente armada por el mismo programador.</li>\n            <li>El diseño debe ser amigable y funcional, permitiendo ordenar columnas y, de ser posible, filtrar/buscar registros por cualquiera de los campos listados.</li>\n            <li>No es necesario acceso web ni conexión remota.</li>\n            <li>No requiere permisos de edición, únicamente visualización, por el momento.</li>\n        </ul>\n        <p>Solicitud hecha el dia <strong>25/07/2025</strong></p>");

        bttn_dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_devActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttn_dev, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(13, 13, 13))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(bttn_dev, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx_ninv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Inv" }));
        cbx_ninv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_ninvActionPerformed(evt);
            }
        });

        cbx_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre" }));
        cbx_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_nameActionPerformed(evt);
            }
        });

        cbx_dir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direccion" }));
        cbx_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_dirActionPerformed(evt);
            }
        });

        cbx_area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Area" }));
        cbx_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_areaActionPerformed(evt);
            }
        });

        cbx_ubicacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ubicacion" }));
        cbx_ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_ubicacionActionPerformed(evt);
            }
        });

        cbx_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado" }));
        cbx_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_statusActionPerformed(evt);
            }
        });

        jLabel2.setText("Caracteristicas :");

        tf_caracteristicas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_caracteristicasKeyTyped(evt);
            }
        });

        jLabel3.setText("No. Inventario");

        jLabel4.setText("Nombre");

        jLabel5.setText("Estado");

        jLabel6.setText("Direccion");

        jLabel7.setText("Area");

        jLabel8.setText("Ubicacion");

        counting_lbl.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_caracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(counting_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_ninv, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_name, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_status, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_area, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbx_ubicacion, 0, 141, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_ninv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_caracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(counting_lbl))
                .addGap(20, 20, 20))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "No Inv", "Marca", "Ubicacion", "Caracteristicas", "Direccion", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_version.setText("version");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_version, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_version, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("Actualizar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem1.setText("Acerca");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1004, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jInternalFrame1.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.add(jInternalFrame1);
        jInternalFrame1.show();
        jInternalFrame1.toFront();
        this.revalidate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cbx_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_areaActionPerformed
        // TODO add your handling code here:
        sel();
    }//GEN-LAST:event_cbx_areaActionPerformed

    private void bttn_devActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_devActionPerformed
        // TODO add your handling code here:
        if(clickcount > 6){
            JPanel panel = new JPanel();
            JLabel label = new JLabel("Enter a password:");
            JPasswordField pass = new JPasswordField(10);
            panel.add(label);
            panel.add(pass);
            String[] options = new String[]{"OK", "Cancel"};
            int option = JOptionPane.showOptionDialog(null, panel, "D",
                                     JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                                     null, options, options[0]);
            if(option == 0) // pressing OK button
            {
                char[] password = pass.getPassword();
                //System.out.println("Your password is: " + new String(password));
                if(new String(password).equals(devpass)){
                    String auxQuery = JOptionPane.showInputDialog("Query: ");
                    //backup -> sqlite3 source_database.db ".backup backup_database.db"
                    System.out.println(auxQuery);
                }
            }
            clickcount=0;
        }
        clickcount++;
    }//GEN-LAST:event_bttn_devActionPerformed

    private void cbx_ninvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_ninvActionPerformed
        // TODO add your handling code here:
        sel();
    }//GEN-LAST:event_cbx_ninvActionPerformed
    private void cbx_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_nameActionPerformed
        // TODO add your handling code here:
        sel();
    }//GEN-LAST:event_cbx_nameActionPerformed
    private void cbx_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_statusActionPerformed
        // TODO add your handling code here:
        sel();
    }//GEN-LAST:event_cbx_statusActionPerformed
    private void cbx_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_dirActionPerformed
        // TODO add your handling code here:
        sel();
    }//GEN-LAST:event_cbx_dirActionPerformed
    private void cbx_ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_ubicacionActionPerformed
        // TODO add your handling code here:
        sel();
    }//GEN-LAST:event_cbx_ubicacionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(clickcount > 2){
            JPanel panel = new JPanel();
            JLabel label = new JLabel("Contraseña:");
            JPasswordField pass = new JPasswordField(10);
            panel.add(label);
            panel.add(pass);
            String[] options = new String[]{"OK", "Cancel"};
            int option = JOptionPane.showOptionDialog(null, panel, "Refill",
                                     JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                                     null, options, options[0]);
            if(option == 0) // pressing OK button
            {
                char[] password = pass.getPassword();
                //System.out.println("Your password is: " + new String(password));
                if(sqlq.getPass(new String(password))){
                    System.out.println("??");
                    DataFill dfill = new DataFill();
                    dfill.setVisible(true);
//                    String yn = "s";
//                    while (yn.equalsIgnoreCase("s")||yn.equalsIgnoreCase("si")) {
//                        String a = JOptionPane.showInputDialog("Empleado o Equipo?");
//
//                        String data[];
//
//                        switch (a.toUpperCase()) {
//                            case "EMPLEADO":
//                                data = new String[5];
//                                data[0] = JOptionPane.showInputDialog("Nombre: ");
//                                data[1] = JOptionPane.showInputDialog("Departamento/Área: ");
//                                data[2] = JOptionPane.showInputDialog("Dirección: ");
//                                data[3] = JOptionPane.showInputDialog("Cargo: ");
//                                data[4] = JOptionPane.showInputDialog("Ubicación: ");
//                                sqlq.insertOnResguardante(data);
//                                break;
//                            case "EQUIPO":
//                                data = new String[8];
//                                data[0] = JOptionPane.showInputDialog("Nombre: ");
//                                data[1] = JOptionPane.showInputDialog("Marca: ");
//                                data[2] = JOptionPane.showInputDialog("Modelo: ");
//                                data[3] = JOptionPane.showInputDialog("Número Inventario: ");
//                                data[4] = JOptionPane.showInputDialog("Número de Serie: ");
//                                data[5] = JOptionPane.showInputDialog("Componentes: \nSeparar por comas");
//                                data[6] = JOptionPane.showInputDialog("Estado: ");
//                                data[7] = JOptionPane.showInputDialog("Observaciones: ");
//                                sqlq.insertOnGabinete(data);
//                                cbx_init();
//                                break;
//                            default:
//                                JOptionPane.showMessageDialog(null, "Opcion invalida");
//                                break;
//                        }
//                        yn = JOptionPane.showInputDialog("Agregar algo mas? (S/N)(Si/No):");
//                    }
                }else {

                }
                //System.out.println(sqlq.getPass(new String(password)));
            }
            clickcount=0;
        }else{
            clickcount++;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf_caracteristicasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_caracteristicasKeyTyped
        // TODO add your handling code here:
        sel();
    }//GEN-LAST:event_tf_caracteristicasKeyTyped

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        sel();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void sel(){
        try{
            String sql = "SELECT r.nombre, r.ubicacion_fisica, r.direccion, r.departamento, h.no_inventario, h.marca, h.componentes FROM datos_resguardante r INNER JOIN hardware_gabinete h ON r.id = h.resguardante ";
            var conn = BD.Connect.open();
            var stmt = conn.createStatement();
            sql = sql + filters();
            ResultSet chk = stmt.executeQuery(sql);
            
            DefaultTableModel mod = (DefaultTableModel) jTable1.getModel();
            
            String arg[] = new String[7];
            
            mod.setRowCount(0);
            
            while(chk.next()){
                arg[0]=chk.getString(1);
                arg[1]=chk.getString(5);
                arg[2]=chk.getString(6);
                arg[3]=chk.getString(2);
                arg[4]=chk.getString(7);
                arg[5]=chk.getString(3);
                arg[6]=chk.getString(4);
                
                mod.addRow(arg);
            }

            co = mod.getRowCount();
            counting_lbl.setText(String.valueOf(co) + " Equipos en lista");

            jTable1.setModel(mod);
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private String filters(){
        String f = " ";
        int c = 0;
        if (cbx_area.getSelectedItem().toString().equalsIgnoreCase("TODO") && cbx_dir.getSelectedItem().toString().equalsIgnoreCase("TODO") && cbx_name.getSelectedItem().toString().equalsIgnoreCase("TODO") && cbx_ninv.getSelectedItem().toString().equalsIgnoreCase("TODO") && cbx_status.getSelectedItem().toString().equalsIgnoreCase("TODO") && cbx_ubicacion.getSelectedItem().toString().equalsIgnoreCase("TODO") && tf_caracteristicas.getText().isBlank()){
            f = " ";
            System.out.println("--"+c);
        }else{
            f = f + "where ";
            if (!cbx_area.getSelectedItem().toString().equalsIgnoreCase("TODO")){
                f = f + "departamento = '"+cbx_area.getSelectedItem().toString()+"' ";
                c++;
            System.out.println("--"+c);
            }
            if (!cbx_dir.getSelectedItem().toString().equalsIgnoreCase("TODO")){
                if(c>0){
                    f = f + ", ";
                }
                f = f + "direccion = '"+cbx_dir.getSelectedItem().toString()+"' ";
                c++;
            System.out.println("--"+c);
            }
            if (!cbx_ubicacion.getSelectedItem().toString().equalsIgnoreCase("TODO")){
                if(c>0){
                    f = f + ", ";
                }
                f = f + "ubicacion_fisica = '"+cbx_ubicacion.getSelectedItem().toString()+"' ";
                c++;
            }
            if (!cbx_status.getSelectedItem().toString().equalsIgnoreCase("TODO")){
                if(c>0){
                    f = f + ", ";
                }
                f = f + "status = '"+cbx_status.getSelectedItem().toString()+"' ";

                c++;
            }
            if (!cbx_ninv.getSelectedItem().toString().equalsIgnoreCase("TODO")){
                if(c>0){
                    f = f + ", ";
                }
                f = f + "no_inventario = '"+cbx_ninv.getSelectedItem().toString()+"' ";
                c++;
            }
            if (!cbx_name.getSelectedItem().toString().equalsIgnoreCase("TODO")){
                if(c>0){
                    f = f + ", ";
                }
                f = f + "nombre = '"+cbx_name.getSelectedItem().toString()+"' ";
                c++;
            }
            if (!tf_caracteristicas.getText().isBlank()){
                if(c>0){
                    f = f + ", ";
                }
                f = f + "componentes like '%"+tf_caracteristicas.getText()+"%'";
            }

        }
        
        
        return f;
    }
    private void cbx_init(){
        try{
            String sql = "SELECT r.nombre, r.ubicacion_fisica, r.direccion, r.departamento, h.no_inventario, h.status FROM datos_resguardante r INNER JOIN hardware_gabinete h ON r.id = h.resguardante ";
            var conn = BD.Connect.open();
            var stmt = conn.createStatement();
            ResultSet chk;
            List<String> lname, lubif, ldir, larea, linv, lstatus;
            //String item = "";
            
            cbx_name.removeAllItems();
            cbx_area.removeAllItems();
            cbx_dir.removeAllItems();
            cbx_ninv.removeAllItems();
            cbx_status.removeAllItems();
            cbx_ubicacion.removeAllItems();

            chk = stmt.executeQuery(sql);
            lname = getUniqueValues(chk, "nombre");
            chk = stmt.executeQuery(sql);
            lubif = getUniqueValues(chk, "ubicacion_fisica");
            chk = stmt.executeQuery(sql);
            ldir = getUniqueValues(chk, "direccion");
            chk = stmt.executeQuery(sql);
            larea = getUniqueValues(chk, "departamento");
            chk = stmt.executeQuery(sql);
            linv = getUniqueValues(chk, "no_inventario");
            chk = stmt.executeQuery(sql);
            lstatus = getUniqueValues(chk, "status");
            
            cbx_name.addItem("TODO");
            cbx_area.addItem("TODO");
            cbx_dir.addItem("TODO");
            cbx_ninv.addItem("TODO");
            cbx_status.addItem("TODO");
            cbx_ubicacion.addItem("TODO");
            
            
            for(String it : lname){
                cbx_name.addItem(it);
            }
            for(String it : larea){
                cbx_area.addItem(it);
            }
            for(String it : ldir){
                cbx_dir.addItem(it);
            }
            for(String it : linv){
                cbx_ninv.addItem(it);
            }
            for(String it : lstatus){
                cbx_status.addItem(it);
            }
            for(String it : lubif){
                cbx_ubicacion.addItem(it);
            }

            cbx_name.setSelectedIndex(0);
            cbx_ninv.setSelectedIndex(0);
            cbx_status.setSelectedIndex(0);
            cbx_area.setSelectedIndex(0);
            cbx_dir.setSelectedIndex(0);
            cbx_ubicacion.setSelectedIndex(0);

            sel();
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e);
        }
    }
       public List<String> getUniqueValues(ResultSet rs, String columnName) throws SQLException {
        Set<String> uniqueSet = new LinkedHashSet<>(); // preserves insertion order


        while (rs.next()) {
            String value = rs.getString(columnName);
            if (value != null) {
                uniqueSet.add(value.trim());
            }
        }

        return new ArrayList<>(uniqueSet);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_dev;
    private javax.swing.JComboBox<String> cbx_area;
    private javax.swing.JComboBox<String> cbx_dir;
    private javax.swing.JComboBox<String> cbx_name;
    private javax.swing.JComboBox<String> cbx_ninv;
    private javax.swing.JComboBox<String> cbx_status;
    private javax.swing.JComboBox<String> cbx_ubicacion;
    private javax.swing.JLabel counting_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_version;
    private javax.swing.JTextField tf_caracteristicas;
    // End of variables declaration//GEN-END:variables
}
